telegram:
  # not real token, taken from https://github.com/nimaxin/init-data-py/blob/master/tests/test_validate.py
  bot_token: "7244657541:AAFMjYH4kc3U9zG0GWnxYfW-QKICVzDwvEw"
  tg_init_data: "query_id=AAF03wc0AgAAAHTfBzTtHPDB&user=%7B%22id%22%3A5167898484%2C%22first_name%22%3A%22xin%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22pvnimaxin%22%2C%22language_code%22%3A%22en%22%2C%22allows_write_to_pm%22%3Atrue%2C%22photo_url%22%3A%22https%3A%5C%2F%5C%2Ft.me%5C%2Fi%5C%2Fuserpic%5C%2F320%5C%2FYpcdHFmoxukmQ537mOZhe-Woot_k2xrmbdAIrGK1zFgIVth6Wzacz7P2nGNCcp9j.svg%22%7D&auth_date=1731441609&hash=f4bac82fe8f20abdc03126af489751752e830227b58241ec2f9dd67913909ee0"
  admin_ids: [1,2,3,4]
  bot_username: "my_bot_username"


postgres:
  host: "localhost"
  port: 5435
  user: "dev_user"
  password: "dev_password"
  db: "ask_app"

auth:
  secret_key: "secret"
  algorithm: "HS256"
  access_token_expire_minutes: 30

log:
  level: "INFO"
