version: '3.8'
name: "test"

services:
  postgres:
    image: postgres:17-alpine
    container_name: ${PG_TEST_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_TEST_USER} -d ${POSTGRES_TEST_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_test_data:
